# Generated by Django 6.0.6 on 2026-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_workerprofile_bio_workerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='jobs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
