# Generated by Django 6.0.6 on 2026-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_workerprofile_jobs_count_workerprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/'),
        ),
    ]
