# Generated by Django 6.0.7 on 2026-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
