# Generated by Django 6.0.7 on 2026-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_booking_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='citizenship_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_citizenship/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
