# Generated by Django 6.0.7 on 2026-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_workerprofile_citizenship_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='response_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
