# Generated by Django 6.0.7 on 2026-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_booking_response_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('flexible', 'Flexible'), ('mornings', 'Mornings'), ('afternoons', 'Afternoons'), ('evenings', 'Evenings')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='category',
            field=models.CharField(choices=[('furniture-assembly', 'Furniture Assembly'), ('wall-mounting', 'Wall Mounting'), ('moving', 'Moving Help'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('gardening', 'Gardening'), ('home-repairs', 'Home Repairs'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-1', 'Less than 1 year'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='Comma-separated, e.g. English, Nepali, Hindi', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
