# Generated by Django 6.0.7 on 2026-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
