# Generated by Django 6.0.7 on 2026-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
